/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.e17cn2.dormitorymanagement.view;

import com.e17cn2.dormitorymanagement.dao.BedDAO;
import com.e17cn2.dormitorymanagement.dao.InvoiceDAO;
import com.e17cn2.dormitorymanagement.dao.RoomDAO;
import com.e17cn2.dormitorymanagement.dao.StudentDAO;
import com.e17cn2.dormitorymanagement.model.entity.Bed;
import com.e17cn2.dormitorymanagement.model.entity.Invoice;
import com.e17cn2.dormitorymanagement.model.entity.Room;
import com.e17cn2.dormitorymanagement.model.entity.Student;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TGDD
 */
public class StudentDebtStatFrm extends javax.swing.JFrame {

   
   
    private DefaultTableModel tblStatStudent;
    private Invoice invoice;
    private Room room;
    private Bed bed;
    
    /**
     * Creates new form StudentDebtStatFrm
     */
    public StudentDebtStatFrm() {
        initComponents();
        initTable();
    }
    
    
    public void initTable(){
        String[] col={"Ma sinh vien","Ten sinh vien","CMT","So DT","Truong","Khoa","Nien Khoa","Ten Phong","Kieu Phong",
        "Ma giuong","Loai Giuong","Tong tien"};
        tblStatStudent=new DefaultTableModel(col,0);
        jTable1.setModel(tblStatStudent);
        
        InvoiceDAO invoiceDAO = new InvoiceDAO();
        RoomDAO roomDAO = new RoomDAO();
        BedDAO bedDAO = new BedDAO();
        StudentDAO studentDAO = new StudentDAO();
       
       ArrayList<Room> listRooms = new ArrayList<>();
       listRooms = roomDAO.getRoom();
       
       ArrayList<Bed> listBeds = new ArrayList<>();
       listBeds = bedDAO.getBed();
       
       ArrayList<Invoice> listInvoices = new ArrayList<>();
       listInvoices = invoiceDAO.getInvoice();
       
       ArrayList<Student> listStudents = new ArrayList<>();
       listStudents = studentDAO.getStudent();
       for (int i =0;i<listStudents.size();i++) {
           tblStatStudent.addRow(new Object[] {listStudents.get(i).getId()+"", listStudents.get(i).getName(), 
               listStudents.get(i).getIdCard(),listStudents.get(i).getPhone(), listStudents.get(i).getSchool(),
               listStudents.get(i).getMajor(), listStudents.get(i).getYear(),listRooms.get(i).getRoomName(), 
               listRooms.get(i).getRoomType(),listRooms.get(i).getRoomName(), listBeds.get(i).getType(),listInvoices.get(i).getAmountUnPaid()+""});
       }
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Bảng Thống Kê Sinh Viên Theo Dư Nợ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
        StudentDAO studentDAO =  new StudentDAO();
        ArrayList<Student> listStudents = studentDAO.getStudent();
        InvoiceDAO invoiceDAO = new InvoiceDAO();
        ArrayList<Invoice> listInvoices = new ArrayList<>();
        listInvoices = invoiceDAO.getInvoice();
        
        int row = jTable1.getSelectedRow();
        Student student = listStudents.get(jTable1.convertRowIndexToModel(row));
        Invoice invoice=listInvoices.get(jTable1.convertRowIndexToModel(row));
        
        
         DetailDebtStudentFrm detailDebtStudentFrm = new DetailDebtStudentFrm(student,invoice);
        detailDebtStudentFrm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDebtStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDebtStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDebtStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDebtStatFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDebtStatFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
